# Generated by Django 4.2.27 on 2026-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('bank_tasks', models.JSONField(default=list)),
                ('wheel_tasks', models.JSONField(default=list)),
                ('is_muted', models.BooleanField(default=False)),
                ('theme_mode', models.CharField(default='auto', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
