# Generated by Django 4.2.27 on 2026-03-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstate',
            name='presets',
            field=models.JSONField(default=list),
        ),
    ]
